name: Update Work Summary

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 12:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch and Format Activity Data
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          # Create a temporary file for new activities
          ACTIVITY_FILE="new-activity.md"
          echo "### Work Summary - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > $ACTIVITY_FILE
          echo "" >> $ACTIVITY_FILE

          # Fetch and Print Data - Uncomment below lines for debugging purposes
          # curl -s -H "Authorization: token $PAT" "https://api.github.com/users/${{ github.actor }}/events" > api-response.json
          # cat api-response.json

          # Fetch events using curl and format with jq
          curl -s -H "Authorization: token $PAT" "https://api.github.com/users/${{ github.actor }}/events" | \
          jq -r '
            .[] |
            select(.type == "PushEvent" or .type == "PullRequestEvent") |
            if .type == "PushEvent" then
              .repo.name as $repo_name | # Store the repository name from the parent context
              .payload.commits[] |
              select(.distinct == true) | # Only include distinct commits
              "- **Commit:** \(.message // "No message provided") in \($repo_name) [↗](https://github.com/\($repo_name)/commit/\(.sha))"
            elif .type == "PullRequestEvent" then
              "- **Pull Request:** \(.payload.pull_request.title // "No title provided") in \(.repo.name // "Unknown repository") [🔗](\(.payload.pull_request.html_url))"
            end
          ' >> $ACTIVITY_FILE

          # Check if there are new activities
          if [ $(wc -l < $ACTIVITY_FILE) -eq 2 ]; then
            echo "No new activities to log. Exiting."
            exit 0
          fi

      - name: Append New Activities to Work Log
        run: |
          cat new-activity.md >> work-summary.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Baby Manisha Sunkara"
          git config --global user.email "babymaneesha@gmail.com"
          git add work-summary.md
          git commit -m "Update work summary: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"
          git push
